// ESM facade over box2dCommandRing.impl.js (one logic source for importScripts + import).
import './box2dCommandRingImpl.js';

const R = globalThis.Box2dCommandRing;

export const BOX2D_CMD = R.BOX2D_CMD;
export const BOX2D_CMD_HEADER_I32 = R.BOX2D_CMD_HEADER_I32;
export const BOX2D_CMD_STRIDE_I32 = R.BOX2D_CMD_STRIDE_I32;
export const BOX2D_CMD_DEFAULT_CAPACITY = R.BOX2D_CMD_DEFAULT_CAPACITY;
export const createCommandRingSab = R.createCommandRingSab;
export const bindCommandRing = R.bindCommandRing;
export const isCommandRingBound = R.isCommandRingBound;
export const setAssertRotCSUnit = R.setAssertRotCSUnit;
export const enqueueSetTransform = R.enqueueSetTransform;
export const enqueueSetVelocity = R.enqueueSetVelocity;
export const enqueueSetRotCS = R.enqueueSetRotCS;
export const enqueueSetAngularVelocity = R.enqueueSetAngularVelocity;
export const enqueueSetFixedRotation = R.enqueueSetFixedRotation;
export const enqueueExplode = R.enqueueExplode;
export const enqueueSetSleepThreshold = R.enqueueSetSleepThreshold;
export const enqueueSetAwake = R.enqueueSetAwake;
export const enqueueCreateParticleSystem = R.enqueueCreateParticleSystem;
export const enqueueSetLiquidFunEmit = R.enqueueSetLiquidFunEmit;
export const enqueueSetLiquidFunLifespan = R.enqueueSetLiquidFunLifespan;
export const enqueueSetLiquidFunScale = R.enqueueSetLiquidFunScale;
export const enqueueSetLiquidFunLight = R.enqueueSetLiquidFunLight;
export const enqueueSetLiquidFunLayers = R.enqueueSetLiquidFunLayers;
export const enqueueSetParticleTuning = R.enqueueSetParticleTuning;
export const enqueueSetGroupViscousScale = R.enqueueSetGroupViscousScale;
export const enqueueJoinParticleGroups = R.enqueueJoinParticleGroups;
export const enqueueSplitParticleGroup = R.enqueueSplitParticleGroup;
export const enqueueParticleApplyForce = R.enqueueParticleApplyForce;
export const enqueueParticleApplyImpulse = R.enqueueParticleApplyImpulse;
export const enqueueGroupApplyForce = R.enqueueGroupApplyForce;
export const enqueueGroupApplyImpulse = R.enqueueGroupApplyImpulse;
export const enqueueCreateParticleGroupBox = R.enqueueCreateParticleGroupBox;
export const enqueueCreateParticleGroupCircle = R.enqueueCreateParticleGroupCircle;
export const enqueueDestroyParticleGroup = R.enqueueDestroyParticleGroup;
export const enqueueDestroyParticleSystem = R.enqueueDestroyParticleSystem;
export const enqueueClearLiquidFunParticles = R.enqueueClearLiquidFunParticles;
export const enqueueSetParticleUserData = R.enqueueSetParticleUserData;
export const enqueueSetParticleUserDataRange = R.enqueueSetParticleUserDataRange;
export const enqueueSetParticleColor = R.enqueueSetParticleColor;
export const enqueueSetParticleColorRange = R.enqueueSetParticleColorRange;
export const enqueueSetParticleFlags = R.enqueueSetParticleFlags;
export const enqueueSetParticleViscousScale = R.enqueueSetParticleViscousScale;
export const enqueueSetParticleViscousScaleRange = R.enqueueSetParticleViscousScaleRange;
export const enqueueSetGroupFlags = R.enqueueSetGroupFlags;
export const enqueueDestroyParticle = R.enqueueDestroyParticle;
export const enqueueCreateParticle = R.enqueueCreateParticle;
export const enqueueSetLiquidFunPayload = R.enqueueSetLiquidFunPayload;
export const enqueueParticleApplyForceRange = R.enqueueParticleApplyForceRange;
export const enqueueParticleApplyImpulseRange = R.enqueueParticleApplyImpulseRange;
export const enqueueExtractParticles = R.enqueueExtractParticles;
export const enqueueSetParticleUserDataList = R.enqueueSetParticleUserDataList;
export const drainCommandRing = R.drainCommandRing;
export const Box2dCommandRing = R;
export default R;
