import { Component } from '../core/Component.js';
import { convertRGBtoBGR } from '../core/utils.js';

export class LightEmitter extends Component {
  static ARRAY_SCHEMA = {
    active: Uint8Array, // 0 = entity doesn't have this component, 1 = active
    lightColor: Uint32Array,
    lightIntensity: Float32Array,
    sqrtLightIntensity: Float32Array,
    height: Float32Array,
    glowHeightOffset: Float32Array,
    hasGlowSprite: Uint8Array, // 0 = no glow sprite, 1 = render glow sprite (default for static lights)
  };

  // Virtual static properties for TypeScript - these are created by Component.initializeArrays()
  // Properties are TypedArrays indexed by entity index: LightEmitter.lightColor[entityIndex]
  /** @static @type {Uint8Array} */
  static active;
  /** @static @type {Uint32Array} */
  static lightColor;
  /** @static @type {Float32Array} */
  static lightIntensity;
  /** @static @type {Float32Array} */
  static sqrtLightIntensity;
  /** @static @type {Float32Array} */
  static height;
  /** @static @type {Float32Array} */
  static glowHeightOffset;
  /** @static @type {Uint8Array} */
  static hasGlowSprite;

  /**
   * Custom getter for lightIntensity
   * Returns the light intensity value
   */
  get lightIntensity() {
    return LightEmitter.lightIntensity[this.index];
  }

  /**
   * Custom setter for lightIntensity
   * OPTIMIZED: Automatically updates sqrtLightIntensity to avoid repeated sqrt calculations
   * This is used in pixi_worker for light culling: influenceRadius = 10 * sqrt(intensity)
   */
  set lightIntensity(value) {
    LightEmitter.lightIntensity[this.index] = value;
    // Cache sqrt(intensity) to avoid recalculating it every frame in hot loops
    LightEmitter.sqrtLightIntensity[this.index] = Math.sqrt(value);
  }

  get lightColor() {
    // Convert BGR back to RGB for user-facing API
    const bgr = LightEmitter.lightColor[this.index];
    // BGR to RGB: swap bytes
    return ((bgr & 0xff) << 16) | (bgr & 0xff00) | ((bgr >> 16) & 0xff);
  }

  set lightColor(value) {
    LightEmitter.lightColor[this.index] = convertRGBtoBGR(value);
  }

  // Virtual instance properties for TypeScript/JSDoc
  // These are auto-generated by Component._createInstanceProperties() at runtime
  // but TypeScript needs these declarations to recognize instance properties
  /** @type {number} Component active state (0 = inactive, 1 = active) */
  active;

  /** @type {number} Height offset for light */
  height;
  /** @type {number} Glow sprite height offset */
  glowHeightOffset;
  /** @type {number} Whether to render glow sprite (0 = no, 1 = yes) */
  hasGlowSprite;

}
