import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const packageJsonPath = path.join(rootDir, 'package.json');
const versionModulePath = path.join(rootDir, 'src', 'version.js');

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version;

const content = `// AUTO-GENERATED by scripts/sync-version.js\nexport const VERSION = '${version}';\n`;

const current = fs.existsSync(versionModulePath)
  ? fs.readFileSync(versionModulePath, 'utf8')
  : null;

if (current !== content) {
  fs.writeFileSync(versionModulePath, content);
  console.log(`Synced src/version.js -> ${version}`);
}
