/**
 * Engine feature catalog for the scoreboard.
 * One row per hot subsystem. Gameplay means a scene that actually runs the code.
 * Artistic demos (Predator combat) are not rows.
 */

export const ENGINE_FEATURES = [
  {
    id: 'ray',
    name: 'Grid Ray DDA',
    module: 'src/core/ray.js',
    kernel: { script: 'tests/bench/rayMicrobench.mjs', opsKey: 'cases.cast.opsPerSec' },
    scene: {
      key: 'rayStress',
      path: '/tests/bench/stressScenes/rayStressScene.js',
      exportName: 'RayStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'rayVsBox2d',
    name: 'Ray vs Box2D busy',
    module: 'src/core/ray.js',
    kernel: { script: 'tests/bench/rayVsBox2dMicrobench.mjs', opsKey: 'cases.weedjs_cast.opsPerSec' },
    scene: {
      key: 'rayVsBox2dBusy',
      path: '/tests/bench/stressScenes/rayVsBox2dStressScene.js',
      exportName: 'RayVsBox2dWeedBusyScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'decals',
    name: 'Decal stamp',
    module: 'src/core/decal.js',
    kernel: { script: 'tests/bench/decalMicrobench.mjs', opsKey: 'cases.normal_multitile_large.opsPerSec' },
    scene: {
      key: 'decalStamp',
      path: '/tests/bench/stressScenes/decalStampStressScene.js',
      exportName: 'DecalStampStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    // Stamp-grid changes how many particle stamps land; tiles uploaded is the work the scene forces.
    load: ['DECAL_TILES_UPLOADED'],
    protocolCeiling:
      'Decal.stamp flood: tiles uploaded match; main particle step stays <3 ms (cv 78% this sitting)',
  },
  {
    id: 'emit',
    name: 'Particle emit',
    module: 'src/core/particleEmitter.js',
    kernel: { script: 'tests/bench/particleEmitMicrobench.mjs', opsKey: 'cases.emitFlat_burst.opsPerSec' },
    scene: {
      key: 'particleEmit',
      path: '/tests/bench/stressScenes/particleEmitStressScene.js',
      exportName: 'ParticleEmitStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_PARTICLES'],
    protocolCeiling: 'Uint16 particle pool (maxParticles 65535); particle step stays ~2.2 ms',
  },
  {
    id: 'integrate',
    name: 'Particle integrate',
    module: 'src/util/particleIntegrate.js',
    // build + updateParticlePhysicsBuffers at 50% pool occupancy. The old key
    // (cases.buildActiveListBuffers) never existed in the JSON.
    kernel: { script: 'tests/bench/particleIntegrateMicrobench.mjs', opsKey: 'cases.occ50_integrate.opsPerSec' },
    scene: {
      key: 'particleIntegrate',
      path: '/tests/bench/stressScenes/particleIntegrateStressScene.js',
      exportName: 'ParticleIntegrateStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_PARTICLES'],
    protocolCeiling: 'Uint16 particle pool (maxParticles 65535); particle step stays ~2.2 ms',
  },
  {
    id: 'spatial',
    name: 'Spatial neighbors',
    module: 'src/workers/spatialWorker.js',
    // Shipped SpatialWorker.rebuildOwnedRows + findNeighborsForOwnedEntities, 3 workers, Predator config.
    kernel: { script: 'tests/bench/spatialWorkerMicrobench.mjs', opsKey: 'cases.frame.opsPerSec' },
    scene: {
      key: 'stationarySpatial',
      path: '/tests/bench/stressScenes/stationarySpatialScene.js',
      exportName: 'StationarySpatialScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['spatialMax_STEP_MS'],
    load: ['BODY_COUNT', 'NEIGHBORS_REUSED'],
  },
  {
    id: 'box2d',
    name: 'Box2D step',
    module: 'src/box2d/weedjsPost.js',
    kernel: null,
    scene: {
      key: 'balls',
      path: '/demos/ballsScene/ballsScene.js',
      exportName: 'BallsScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT', 'AWAKE_COUNT'],
  },
  {
    id: 'liquidfun',
    name: 'LiquidFun particle step',
    module: 'src/box2d/weedjsPost.js',
    kernel: {
      script: 'tests/bench/liquidFunPassProfileMicrobench.mjs',
      opsKey: 'worlds.workers1.lfMedianMs',
      higherBetter: false,
    },
    scene: {
      key: 'liquidFunStress',
      path: '/tests/bench/stressScenes/liquidFunStressScene.js',
      exportName: 'LiquidFunStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'liquidfunCouple',
    name: 'LiquidFun body couple',
    module: 'src/box2d/weedjsPost.js',
    kernel: {
      script: 'tests/bench/liquidFunBodyCoupleMicrobench.mjs',
      opsKey: 'scenes.a2-crates48.lfMedianMs',
      higherBetter: false,
    },
    scene: {
      key: 'liquidFunBodyCouple',
      path: '/tests/bench/stressScenes/liquidFunBodyCoupleStressScene.js',
      exportName: 'LiquidFunBodyCoupleStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'liquidfunQuery',
    name: 'LiquidFun query',
    module: 'src/box2d/liquidFunQuery.js',
    kernel: null,
    scene: {
      key: 'liquidFunQuery',
      path: '/tests/bench/stressScenes/liquidFunQueryStressScene.js',
      exportName: 'LiquidFunQueryStressScene',
      headed: false,
      kind: 'stress',
    },
    // Query AABB/ray churn is serviced in the physics worker; logic0 is wait + JS dispatch (cv ~27% here).
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'queryAabb',
    name: 'Box2D QueryAABB',
    module: 'src/box2d/box2dQueryAabb.js',
    kernel: null,
    scene: {
      key: 'queryAabb',
      path: '/tests/bench/stressScenes/queryAabbStressScene.js',
      exportName: 'QueryAabbStressScene',
      headed: false,
      kind: 'stress',
    },
    // QueryAABB is issued from logic tick (QueryAabbChurnProbe), not the Box2D step.
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'nav',
    name: 'NavGrid',
    module: 'src/core/navGrid.js',
    kernel: { script: 'tests/bench/navGridMicrobench.mjs', opsKey: 'cases.dijkstra.opsPerSec' },
    scene: {
      key: 'navStress',
      path: '/tests/bench/stressScenes/navStressScene.js',
      exportName: 'NavStressScene',
      headed: false,
      kind: 'stress',
    },
    // Dijkstra / flowfields run on the particle worker, not logic0.
    primary: ['particle_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
    protocolCeiling:
      'dijkstra is the kernel; NavGrid.requestVector does not run flowfields on particle (~0.013 ms)',
  },
  {
    id: 'visPoly',
    name: 'Visibility polygons',
    module: 'src/render/visibility/angularSweep.js',
    kernel: {
      script: 'tests/bench/angularSweepMicrobench.mjs',
      opsKey: 'cases.sweep.opsPerSec',
      informational: true,
    },
    scene: {
      key: 'visPoly',
      path: '/tests/bench/stressScenes/visPolyStressScene.js',
      exportName: 'VisPolyStressScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['preRender_STEP_MS', 'VISIBILITY_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'tilemap',
    name: 'TileMap queries',
    module: 'src/core/tileMap.js',
    kernel: { script: 'tests/bench/tileMapMicrobench.mjs', opsKey: 'cases.getTileId.opsPerSec' },
    scene: {
      key: 'tilemapStress',
      path: '/tests/bench/stressScenes/tilemapStressScene.js',
      exportName: 'TilemapStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'tilemapGid',
    name: 'Tilemap GPU GID pages',
    module: 'src/render/tilemapGid.js',
    // packGidPageRgba8 is the GPU work per page; listGidPages is the cheap index walk.
    kernel: { script: 'tests/bench/tilemapGidMicrobench.mjs', opsKey: 'cases.packGidPageRgba8.opsPerSec' },
    scene: {
      key: 'tilemapGid',
      path: '/tests/bench/stressScenes/tilemapCullStressScene.js',
      exportName: 'TilemapCullStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
    protocolCeiling: '64×64 GID map never spends 3 ms in pixi; kernel is packGidPageRgba8',
  },
  {
    id: 'contactDrain',
    name: 'Box2D contact drain',
    module: 'src/workers/logicWorker.js',
    // Real LogicWorker drain + stay; dense = Predator fixture pairs with sensor-like reach.
    kernel: { script: 'tests/bench/contactsMicrobench.mjs', opsKey: 'cases.dense.opsPerSec' },
    scene: {
      key: 'contactDrain',
      path: '/tests/bench/stressScenes/contactDrainStressScene.js',
      exportName: 'ContactDrainStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
    protocolCeiling: '2048 overlapping contacts: logic0 1.3 ms; 3 ms would saturate physics first',
  },
  {
    id: 'box2dRayJs',
    name: 'Box2D castRayClosest JS service',
    module: 'src/box2d/weedjsPost.js',
    kernel: null,
    scene: {
      key: 'rayVsBox2dBoxBusy',
      path: '/tests/bench/stressScenes/rayVsBox2dStressScene.js',
      exportName: 'RayVsBox2dBoxBusyScene',
      headed: false,
      kind: 'stress',
    },
    // Ray servicing is logic0 (~50 ms); BOX2D_RAYCAST_MS is a detailed-stats subtimer and is 0 with stats off.
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'queryPublish',
    name: 'QuerySystem publish',
    module: 'src/core/querySystem.js',
    kernel: { script: 'tests/bench/querySystemMicrobench.mjs', opsKey: 'cases.publish.opsPerSec' },
    scene: {
      key: 'queryChurn',
      path: '/tests/bench/stressScenes/queryChurnScene.js',
      exportName: 'QueryChurnScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
    protocolCeiling: '8192 entities + 48 churn: logic0 1.2 ms; publish never reaches the 3 ms floor',
  },
  {
    id: 'preRender',
    name: 'Pre-render cull',
    module: 'src/workers/preRenderWorker.js',
    // Flag bitpack variant, not the shipped cull; the pre-render product kernels
    // are the gpuQueue / shadowStamp / painterOrder rows.
    kernel: { script: 'tests/bench/srFlagsMicrobench.mjs', opsKey: 'timings.cull.packed.opsPerSec', informational: true },
    scene: {
      key: 'renderQueue',
      path: '/tests/bench/stressScenes/renderQueueStressScene.js',
      exportName: 'RenderQueueStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['preRender_STEP_MS'],
    load: ['ENTITIES_PROCESSED', 'VISIBLE_ENTITIES'],
    protocolCeiling:
      'linear cull vs main; ~20k visibles, baseline preRender 2.6 ms stays under the 3 ms floor',
  },
  {
    id: 'compute',
    name: 'WebGPU compute pack',
    module: 'src/render/webgpu/computeLayer.js',
    // Primary is n=512 no-sweep: product-scale pack. results.0 (n=64) was cold-start noise.
    kernel: { script: 'tests/bench/computePackMicrobench.mjs', opsKey: 'results.2.opsPerSec' },
    scene: {
      key: 'computeStress',
      path: '/tests/bench/stressScenes/computeStressScene.js',
      exportName: 'ComputeStressScene',
      headed: true,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT'],
    protocolCeiling: '256 boxes, 512²×40 iterate: pixi stays ~0.5 ms (GPU pack is the kernel)',
  },
  {
    id: 'decorations',
    name: 'Decorations spatial',
    module: 'src/core/decorationSpatial.js',
    kernel: { script: 'tests/bench/decorationSpatialMicrobench.mjs', opsKey: 'cases.queryCircle.opsPerSec' },
    scene: {
      key: 'decoQueryCircle',
      path: '/tests/bench/stressScenes/decoQueryCircleStressScene.js',
      exportName: 'DecoQueryCircleStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ACTIVE_DECORATIONS'],
  },
  {
    id: 'bullets',
    name: 'Bullet tick',
    module: 'src/core/bulletPool.js',
    kernel: {
      script: 'tests/bench/bulletTickMicrobench.mjs',
      opsKey: 'cases.tickCrowded.opsPerSec',
      informational: true,
    },
    scene: {
      key: 'bulletStress',
      path: '/tests/bench/stressScenes/bulletStressScene.js',
      exportName: 'BulletStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_BULLETS'],
  },
  {
    id: 'spawn',
    name: 'Treiber spawn storm',
    module: 'src/util/atomicFreeList.js',
    kernel: { script: 'tests/bench/treiberMicrobench.mjs', opsKey: 'cases.batchPop.opsPerSec' },
    scene: {
      key: 'spawnStorm',
      path: '/tests/bench/stressScenes/spawnStormScene.js',
      exportName: 'SpawnStormScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'steadyCombat',
    name: 'Steady combat load',
    module: 'src/workers/particleWorker.js',
    kernel: null,
    scene: {
      key: 'steadyCombat',
      path: '/tests/bench/stressScenes/steadyCombatScene.js',
      exportName: 'SteadyCombatScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['particle_STEP_MS', 'spatialMax_STEP_MS', 'logic0_STEP_MS'],
    load: ['BODY_COUNT', 'ACTIVE_PARTICLES'],
  },
  {
    id: 'decalBlit',
    name: 'Decal tile blit',
    module: 'src/render/decalBlitPack.js',
    kernel: {
      script: 'tests/bench/decalBlitPackMicrobench.mjs',
      opsKey: 'packDecalBlit.opsPerSec',
      // INSTANCED_SPRITE_FLOATS 15→16; do not score kernel vs main. Scene pixi is the product.
      informational: true,
    },
    scene: {
      key: 'decalBlit',
      path: '/tests/bench/stressScenes/decalBlitStressScene.js',
      exportName: 'DecalBlitStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['DECAL_TILES_UPLOADED'],
  },
  {
    id: 'sceneryCam',
    name: 'Scenery camera',
    module: 'src/render/sceneryCamPack.js',
    kernel: { script: 'tests/bench/sceneryCamMicrobench.mjs', opsKey: 'pack.opsPerSec' },
    scene: {
      key: 'sceneryCam',
      path: '/tests/bench/stressScenes/sceneryCamStressScene.js',
      exportName: 'SceneryCamStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['SCENERY_COUNT'],
    protocolCeiling: 'Layer.MAX_LAYERS 16 (12 scenery + built-ins); pixi stays ~0.2 ms',
  },
  {
    id: 'meshFillMoving',
    name: 'MESH fill moving pack',
    module: 'src/render/colliderFillBatch.js',
    kernel: { script: 'tests/bench/colliderFillPackMicrobench.mjs', opsKey: 'B.opsPerSec' },
    scene: {
      key: 'meshFillMoving',
      path: '/tests/bench/stressScenes/meshFillMovingScene.js',
      exportName: 'MeshFillMovingScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'meshFillPan',
    name: 'MESH fill camera pan',
    module: 'src/render/meshFillCamera.js',
    kernel: { script: 'tests/bench/meshCameraUniformMicrobench.mjs', opsKey: 'timed.opsPerSec' },
    scene: {
      key: 'meshFillPan',
      path: '/tests/bench/stressScenes/meshFillPanScene.js',
      exportName: 'MeshFillPanScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT', 'MESH_FILL_INSTANCES', 'MESH_RT_DRAWS'],
    protocolCeiling: 'static MESH + camera pan skips the pack; pixi stays ≪ 3 ms',
  },
  {
    id: 'meshFillLook',
    name: 'MESH look pan',
    module: 'src/render/meshLookUv.js',
    kernel: null,
    scene: {
      key: 'meshFillLook',
      path: '/tests/bench/stressScenes/meshFillLookPanScene.js',
      exportName: 'MeshFillLookPanScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT', 'MESH_FILL_INSTANCES', 'MESH_RT_DRAWS'],
    protocolCeiling: 'MESH look pan skips the pack; pixi stays ≪ 3 ms',
  },
  // Kernel-only rows: no stress scene reaches their regime; the product gate is
  // Predator ABAB (runPredatorAbab.mjs) on the worker named in `primary`.
  {
    id: 'audioSlots',
    name: 'SoundManager slot claim',
    module: 'src/core/soundManager.js',
    // Predator saturates all 2048 slots; 3 logic workers claim at once.
    kernel: { script: 'tests/bench/audioSlotMicrobench.mjs', opsKey: 'cases.occ100x3.opsPerSec' },
    scene: null,
    primary: ['logic0_STEP_MS'],
    load: [],
  },
  {
    id: 'gameObjectAccess',
    name: 'GameObject component and neighbor access',
    module: 'src/core/gameObject.js',
    kernel: { script: 'tests/bench/gameObjectAccessMicrobench.mjs', opsKey: 'cases.tick.opsPerSec' },
    scene: null,
    primary: ['logic0_STEP_MS'],
    load: [],
  },
  {
    id: 'shadowStamp',
    name: 'Shadow caster stamp',
    module: 'src/render/gpuShadowCasters.js',
    kernel: { script: 'tests/bench/shadowStampMicrobench.mjs', opsKey: 'cases.stamp.opsPerSec' },
    scene: null,
    primary: ['preRender_STEP_MS'],
    load: [],
  },
  {
    id: 'gpuQueuePack',
    name: 'GPU queue instance pack',
    module: 'src/render/gpuQueueLayout.js',
    kernel: { script: 'tests/bench/gpuQueuePackMicrobench.mjs', opsKey: 'cases.sprites.opsPerSec' },
    scene: null,
    primary: ['pixi_STEP_MS'],
    load: [],
  },
  {
    id: 'decalPremultiply',
    name: 'Decal tile premultiply',
    module: 'src/render/webgpu/pinGpuTexture.js',
    kernel: { script: 'tests/bench/premultiplyMicrobench.mjs', opsKey: 'cases.tiles.opsPerSec' },
    scene: null,
    primary: ['pixi_STEP_MS'],
    load: [],
  },
  {
    id: 'painterRadix',
    name: 'Painter radix rebuild',
    module: 'src/util/sortIndexByKey.js',
    kernel: { script: 'tests/bench/painterRadixMicrobench.mjs', opsKey: 'cases.mixed.opsPerSec' },
    scene: null,
    primary: ['pixi_STEP_MS'],
    load: [],
  },
  {
    id: 'publishPose',
    name: 'Physics pose publish',
    module: 'src/box2d/weedjsPost.js',
    kernel: { script: 'tests/bench/publishPoseMicrobench.mjs', opsKey: 'cases.publish.opsPerSec' },
    scene: null,
    primary: ['physics_STEP_MS'],
    load: [],
  },
  {
    id: 'preRenderWorker',
    name: 'Pre-render emitSpriteQueue',
    module: 'src/workers/preRenderWorker.js',
    kernel: { script: 'tests/bench/preRenderWorkerMicrobench.mjs', opsKey: 'cases.emit.opsPerSec' },
    scene: null,
    primary: ['preRender_STEP_MS'],
    load: [],
  },
  {
    id: 'swayBuckets',
    name: 'Decoration sway frequency buckets',
    module: 'src/workers/particleWorker.js',
    kernel: { script: 'tests/bench/swayBucketMicrobench.mjs', opsKey: 'cases.n20k.opsPerSec' },
    scene: null,
    primary: ['particle_STEP_MS'],
    load: [],
  },
];

export function getFeature(id) {
  return ENGINE_FEATURES.find((f) => f.id === id) || null;
}

export function filterFeatures(only) {
  if (!only || !only.length) return ENGINE_FEATURES;
  const set = new Set(only);
  return ENGINE_FEATURES.filter((f) => set.has(f.id));
}
