/**
 * Engine feature catalog for the scoreboard.
 * One row per hot subsystem. Gameplay means a scene that actually runs the code.
 * Artistic demos (Predator combat) are not rows.
 */

export const ENGINE_FEATURES = [
  {
    id: 'ray',
    name: 'Grid Ray DDA',
    module: 'src/core/ray.js',
    kernel: { script: 'tests/bench/rayMicrobench.mjs', opsKey: 'cases.cast.opsPerSec' },
    scene: {
      key: 'rayStress',
      path: '/tests/bench/stressScenes/rayStressScene.js',
      exportName: 'RayStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_RAYCAST_MS', 'logic0_STEP_MS'],
    load: ['logic0_RAYCAST_COUNT'],
  },
  {
    id: 'rayVsBox2d',
    name: 'Ray vs Box2D busy',
    module: 'src/core/ray.js',
    kernel: { script: 'tests/bench/rayVsBox2dMicrobench.mjs', opsKey: 'cases.weedjs_cast.opsPerSec' },
    scene: {
      key: 'rayVsBox2dBusy',
      path: '/tests/bench/stressScenes/rayVsBox2dStressScene.js',
      exportName: 'RayVsBox2dWeedBusyScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_RAYCAST_MS', 'physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'decals',
    name: 'Decal stamp',
    module: 'src/util/decalStamp.js',
    kernel: { script: 'tests/bench/decalMicrobench.mjs', opsKey: 'cases.normal_multitile_large.opsPerSec' },
    scene: {
      key: 'decalStamp',
      path: '/tests/bench/stressScenes/decalStampStressScene.js',
      exportName: 'DecalStampStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['PARTICLES_STAMPED'],
  },
  {
    id: 'emit',
    name: 'Particle emit',
    module: 'src/core/particleEmitter.js',
    kernel: { script: 'tests/bench/particleEmitMicrobench.mjs', opsKey: 'cases.emitFlat_burst.opsPerSec' },
    scene: {
      key: 'particleEmit',
      path: '/tests/bench/stressScenes/particleEmitStressScene.js',
      exportName: 'ParticleEmitStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_PARTICLES'],
  },
  {
    id: 'integrate',
    name: 'Particle integrate',
    module: 'src/util/particleIntegrate.js',
    kernel: { script: 'tests/bench/particleIntegrateMicrobench.mjs', opsKey: 'cases.buildActiveListBuffers.opsPerSec' },
    scene: {
      key: 'particleIntegrate',
      path: '/tests/bench/stressScenes/particleIntegrateStressScene.js',
      exportName: 'ParticleIntegrateStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_PARTICLES'],
  },
  {
    id: 'spatial',
    name: 'Spatial neighbors',
    module: 'src/workers/spatialWorker.js',
    kernel: { script: 'tests/bench/spatialMicrobench.mjs', opsKey: 'cases.c17_hash.opsPerSec' },
    scene: {
      key: 'stationarySpatial',
      path: '/tests/bench/stressScenes/stationarySpatialScene.js',
      exportName: 'StationarySpatialScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['spatialMax_STEP_MS'],
    load: ['BODY_COUNT', 'NEIGHBORS_REUSED'],
  },
  {
    id: 'box2d',
    name: 'Box2D step',
    module: 'src/box2d/weedjsPost.js',
    kernel: null,
    scene: {
      key: 'balls',
      path: '/demos/ballsScene/ballsScene.js',
      exportName: 'BallsScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT', 'AWAKE_COUNT'],
  },
  {
    id: 'liquidfun',
    name: 'LiquidFun particle step',
    module: 'src/box2d/weedjsPost.js',
    kernel: {
      script: 'tests/bench/liquidFunPassProfileMicrobench.mjs',
      opsKey: 'worlds.workers1.lfMedianMs',
      higherBetter: false,
    },
    scene: {
      key: 'liquidFunStress',
      path: '/tests/bench/stressScenes/liquidFunStressScene.js',
      exportName: 'LiquidFunStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'liquidfunCouple',
    name: 'LiquidFun body couple',
    module: 'src/box2d/weedjsPost.js',
    kernel: {
      script: 'tests/bench/liquidFunBodyCoupleMicrobench.mjs',
      opsKey: 'scenes.a2-crates48.lfMedianMs',
      higherBetter: false,
    },
    scene: {
      key: 'liquidFunBodyCouple',
      path: '/tests/bench/stressScenes/liquidFunBodyCoupleStressScene.js',
      exportName: 'LiquidFunBodyCoupleStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'liquidfunQuery',
    name: 'LiquidFun query',
    module: 'src/box2d/liquidFunQuery.js',
    kernel: null,
    scene: {
      key: 'liquidFunQuery',
      path: '/tests/bench/stressScenes/liquidFunQueryStressScene.js',
      exportName: 'LiquidFunQueryStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS', 'logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'queryAabb',
    name: 'Box2D QueryAABB',
    module: 'src/box2d/box2dQueryAabb.js',
    kernel: null,
    scene: {
      key: 'queryAabb',
      path: '/tests/bench/stressScenes/queryAabbStressScene.js',
      exportName: 'QueryAabbStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'nav',
    name: 'NavGrid',
    module: 'src/core/navGrid.js',
    kernel: { script: 'tests/bench/navGridMicrobench.mjs', opsKey: 'cases.dijkstra.opsPerSec' },
    scene: {
      key: 'navStress',
      path: '/tests/bench/stressScenes/navStressScene.js',
      exportName: 'NavStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'visPoly',
    name: 'Visibility polygons',
    module: 'src/render/visibility/angularSweep.js',
    kernel: { script: 'tests/bench/angularSweepMicrobench.mjs', opsKey: 'cases.sweep.opsPerSec' },
    scene: {
      key: 'visPoly',
      path: '/tests/bench/stressScenes/visPolyStressScene.js',
      exportName: 'VisPolyStressScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['preRender_STEP_MS', 'VISIBILITY_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'tilemap',
    name: 'TileMap queries',
    module: 'src/core/tileMap.js',
    kernel: { script: 'tests/bench/tileMapMicrobench.mjs', opsKey: 'cases.getTileId.opsPerSec' },
    scene: {
      key: 'tilemapStress',
      path: '/tests/bench/stressScenes/tilemapStressScene.js',
      exportName: 'TilemapStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'tilemapCull',
    name: 'Tilemap viewport chunk cull',
    module: 'src/render/tilemapCull.js',
    kernel: { script: 'tests/bench/tilemapCullMicrobench.mjs', opsKey: 'cases.listVisibleChunks.opsPerSec' },
    scene: {
      key: 'tilemapCull',
      path: '/tests/bench/stressScenes/tilemapCullStressScene.js',
      exportName: 'TilemapCullStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'contactDrain',
    name: 'Box2D contact drain',
    module: 'src/workers/logicWorker.js',
    kernel: null,
    scene: {
      key: 'contactDrain',
      path: '/tests/bench/stressScenes/contactDrainStressScene.js',
      exportName: 'ContactDrainStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'box2dRayJs',
    name: 'Box2D castRayClosest JS service',
    module: 'src/box2d/weedjsPost.js',
    kernel: null,
    scene: {
      key: 'rayVsBox2dBoxBusy',
      path: '/tests/bench/stressScenes/rayVsBox2dStressScene.js',
      exportName: 'RayVsBox2dBoxBusyScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['physics_STEP_MS', 'logic0_RAYCAST_MS'],
    load: ['BODY_COUNT', 'logic0_RAYCAST_COUNT'],
  },
  {
    id: 'queryPublish',
    name: 'QuerySystem publish',
    module: 'src/core/querySystem.js',
    kernel: { script: 'tests/bench/querySystemMicrobench.mjs', opsKey: 'cases.publish.opsPerSec' },
    scene: {
      key: 'queryChurn',
      path: '/tests/bench/stressScenes/queryChurnScene.js',
      exportName: 'QueryChurnScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'preRender',
    name: 'Pre-render cull',
    module: 'src/workers/preRenderWorker.js',
    kernel: { script: 'tests/bench/srFlagsMicrobench.mjs', opsKey: 'timings.cull.packed.opsPerSec' },
    scene: {
      key: 'renderQueue',
      path: '/tests/bench/stressScenes/renderQueueStressScene.js',
      exportName: 'RenderQueueStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['preRender_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'compute',
    name: 'WebGPU compute pack',
    module: 'src/render/webgpu/computeLayer.js',
    kernel: { script: 'tests/bench/computePackMicrobench.mjs', opsKey: 'results.0.opsPerSec' },
    scene: {
      key: 'computeStress',
      path: '/tests/bench/stressScenes/computeStressScene.js',
      exportName: 'ComputeStressScene',
      headed: true,
      kind: 'stress',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'decorations',
    name: 'Decorations spatial',
    module: 'src/core/decorationSpatial.js',
    kernel: { script: 'tests/bench/decorationSpatialMicrobench.mjs', opsKey: 'cases.queryCircle.opsPerSec' },
    scene: {
      key: 'zenithal',
      path: '/demos/zenithalParticleTestScene/zenithalParticleTestScene.js',
      exportName: 'ZenithalParticleTestScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['pixi_STEP_MS'],
    load: ['BODY_COUNT'],
  },
  {
    id: 'bullets',
    name: 'Bullet tick',
    module: 'src/core/bulletPool.js',
    kernel: { script: 'tests/bench/bulletTickMicrobench.mjs', opsKey: 'cases.tickCrowded.opsPerSec' },
    scene: {
      key: 'bulletStress',
      path: '/tests/bench/stressScenes/bulletStressScene.js',
      exportName: 'BulletStressScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['particle_STEP_MS'],
    load: ['ACTIVE_BULLETS'],
  },
  {
    id: 'spawn',
    name: 'Treiber spawn storm',
    module: 'src/util/atomicFreeList.js',
    kernel: { script: 'tests/bench/treiberMicrobench.mjs', opsKey: 'cases.batchPop.opsPerSec' },
    scene: {
      key: 'spawnStorm',
      path: '/tests/bench/stressScenes/spawnStormScene.js',
      exportName: 'SpawnStormScene',
      headed: false,
      kind: 'stress',
    },
    primary: ['logic0_STEP_MS'],
    load: ['ENTITIES_PROCESSED'],
  },
  {
    id: 'steadyCombat',
    name: 'Steady combat load',
    module: 'src/workers/particleWorker.js',
    kernel: null,
    scene: {
      key: 'steadyCombat',
      path: '/tests/bench/stressScenes/steadyCombatScene.js',
      exportName: 'SteadyCombatScene',
      headed: true,
      kind: 'gameplay',
    },
    primary: ['particle_STEP_MS', 'spatialMax_STEP_MS', 'logic0_STEP_MS'],
    load: ['BODY_COUNT', 'ACTIVE_PARTICLES'],
  },
];

export function getFeature(id) {
  return ENGINE_FEATURES.find((f) => f.id === id) || null;
}

export function filterFeatures(only) {
  if (!only || !only.length) return ENGINE_FEATURES;
  const set = new Set(only);
  return ENGINE_FEATURES.filter((f) => set.has(f.id));
}
