// ExplosionComponent.js - Data for explosion entities
// Tracks lifecycle, intensity, radius growth/shrink, and visual state

import { Component } from '/src/core/Component.js';

export class ExplosionComponent extends Component {
  static ARRAY_SCHEMA = {
    // === Lifecycle ===
    lifespan: Float32Array, // Total lifetime in ms
    elapsedTime: Float32Array, // Time alive so far in ms
    justSpawned: Uint8Array, // Flag to ensure clean state on first tick (1 = just spawned)

    // === Intensity & Radius ===
    wantedIntensity: Float32Array, // Target max light intensity
    maxRadius: Float32Array, // Maximum collider radius at 50% progress

    // === Animation ===
    frameCount: Uint8Array, // Number of frames in current animation (10 or 12)
    baseScale: Float32Array, // Base scale value for the explosion
    flipped: Uint8Array, // Whether sprite is horizontally flipped (1 = flipped)

    // === Cached values ===
    originalWidth: Float32Array, // Cached original sprite width
  };

  // Virtual static properties for TypeScript - these are created by Component.initializeArrays()
  // Properties are TypedArrays indexed by entity index: ExplosionComponent.lifespan[entityIndex]
  /** @static @type {Float32Array} */
  static lifespan;
  /** @static @type {Float32Array} */
  static elapsedTime;
  /** @static @type {Uint8Array} */
  static justSpawned;
  /** @static @type {Float32Array} */
  static wantedIntensity;
  /** @static @type {Float32Array} */
  static maxRadius;
  /** @static @type {Uint8Array} */
  static frameCount;
  /** @static @type {Float32Array} */
  static baseScale;
  /** @static @type {Uint8Array} */
  static flipped;
  /** @static @type {Float32Array} */
  static originalWidth;

  // Virtual instance properties for TypeScript/JSDoc
  // These are auto-generated by Component._createInstanceProperties() at runtime
  // but TypeScript needs these declarations to recognize instance properties
  /** @type {number} Total lifetime in ms */
  lifespan;
  /** @type {number} Time alive so far in ms */
  elapsedTime;
  /** @type {number} Flag to ensure clean state on first tick (1 = just spawned) */
  justSpawned;
  /** @type {number} Target max light intensity */
  wantedIntensity;
  /** @type {number} Maximum collider radius at 50% progress */
  maxRadius;
  /** @type {number} Number of frames in current animation (10 or 12) */
  frameCount;
  /** @type {number} Base scale value for the explosion */
  baseScale;
  /** @type {number} Whether sprite is horizontally flipped (1 = flipped) */
  flipped;
  /** @type {number} Cached original sprite width */
  originalWidth;
}
