// ExplosionComponent.js - Data for explosion entities
// Tracks lifecycle, intensity, radius growth/shrink, and visual state

import { Component } from '/src/core/Component.js';

export class LootableComponent extends Component {
  static ARRAY_SCHEMA = {
    health: Float32Array,
    // resistance moved to static class property
    dropMoney: Float32Array,
    dropPistol: Float32Array,
    dropMachineGun: Float32Array,
    dropStick: Float32Array,
    dropArmor: Float32Array,
    explosionPower: Float32Array,
  };

  // Virtual static properties for TypeScript - these are created by Component.initializeArrays()
  // Properties are TypedArrays indexed by entity index: LootableComponent.health[entityIndex]
  // Pattern: For each property in ARRAY_SCHEMA, add: /** @static @type {TypedArray} */ static propertyName;
  /** @static @type {Float32Array} */
  static health;
  /** @static @type {Float32Array} */
  static dropMoney;
  /** @static @type {Float32Array} */
  static dropPistol;
  /** @static @type {Float32Array} */
  static dropMachineGun;
  /** @static @type {Float32Array} */
  static dropStick;
  /** @static @type {Float32Array} */
  static dropArmor;
  /** @static @type {Float32Array} */
  static explosionPower;

  // Virtual instance properties for TypeScript/JSDoc
  // These are auto-generated by Component._createInstanceProperties() at runtime
  // but TypeScript needs these declarations to recognize instance properties
  /** @type {number} */ health;
  /** @type {number} */ dropMoney;
  /** @type {number} */ dropPistol;
  /** @type {number} */ dropMachineGun;
  /** @type {number} */ dropStick;
  /** @type {number} */ dropArmor;
  /** @type {number} */ explosionPower;
}
